// Parses a WordPress WXR export and emits supabase/migrations/015_blog_posts_seed.sql.
// One-shot: run with `node scripts/blog-import/parse-wxr.mjs <input.xml> <output.sql>`.
// Defaults: input = post.xml, output = supabase/migrations/015_blog_posts_seed.sql.
//
// Skips attachments, drafts, "Uncategorized" category. Strips WordPress block
// comments (<!-- wp:paragraph --> etc.) from content. Leaves inline image URLs
// pointing at the legacy site — good enough while that site is still up.

import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const [, , inputArg, outputArg] = process.argv;
const inputPath = resolve(inputArg || 'post.xml');
const outputPath = resolve(outputArg || 'supabase/migrations/015_blog_posts_seed.sql');

const xml = readFileSync(inputPath, 'utf8');

// Split on </item> so each chunk contains one <item> start-to-end.
const itemChunks = xml.split('</item>').slice(0, -1).map((c) => c.split('<item>')[1]).filter(Boolean);

const sqlEscape = (s) => (s == null ? 'NULL' : `'${String(s).replace(/'/g, "''")}'`);

const cdata = (chunk, tag) => {
  const re = new RegExp(`<${tag}>\\s*<!\\[CDATA\\[([\\s\\S]*?)\\]\\]>\\s*</${tag}>`);
  const m = chunk.match(re);
  return m ? m[1] : null;
};

const plainTag = (chunk, tag) => {
  const re = new RegExp(`<${tag}>([\\s\\S]*?)</${tag}>`);
  const m = chunk.match(re);
  return m ? m[1] : null;
};

const stripWpBlockComments = (html) =>
  html
    .replace(/<!--\s*\/?wp:[^>]*-->/g, '')       // <!-- wp:paragraph --> and <!-- /wp:paragraph -->
    .replace(/^\s*\n/gm, '')
    .trim();

const htmlToText = (html) =>
  html
    .replace(/<[^>]+>/g, ' ')
    .replace(/&nbsp;/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#8230;|&hellip;/g, '…')
    .replace(/&#\d+;/g, '')
    .replace(/\s+/g, ' ')
    .trim();

const decodeSlug = (name) => {
  try {
    return decodeURIComponent(name || '');
  } catch {
    return name || '';
  }
};

const toIsoUtc = (wpDate) => {
  // WordPress gives "2019-01-21 17:38:35" — treat as UTC (we use post_date_gmt).
  if (!wpDate) return null;
  return `${wpDate.replace(' ', 'T')}Z`;
};

const rows = [];
let skipped = { drafts: 0, attachments: 0 };

for (const chunk of itemChunks) {
  const postType = cdata(chunk, 'wp:post_type');
  if (postType !== 'post') {
    if (postType === 'attachment') skipped.attachments += 1;
    continue;
  }
  const status = cdata(chunk, 'wp:status');
  if (status !== 'publish') {
    skipped.drafts += 1;
    continue;
  }

  const title = cdata(chunk, 'title') || plainTag(chunk, 'title') || '(ללא כותרת)';
  const sourcePostId = parseInt(plainTag(chunk, 'wp:post_id') || '0', 10);
  const rawContent = cdata(chunk, 'content:encoded') || '';
  const content = stripWpBlockComments(rawContent);
  const rawExcerpt = cdata(chunk, 'excerpt:encoded') || '';
  const excerpt = (htmlToText(rawExcerpt) || htmlToText(content)).slice(0, 280) || null;
  const slug = decodeSlug(cdata(chunk, 'wp:post_name'));
  const publishedAt = toIsoUtc(cdata(chunk, 'wp:post_date_gmt'));

  // Categories — take the first non-Uncategorized one.
  const categories = [...chunk.matchAll(/<category domain="category"[^>]*><!\[CDATA\[([^\]]+)\]\]><\/category>/g)]
    .map((m) => m[1])
    .filter((c) => c && c.toLowerCase() !== 'uncategorized');
  const category = categories[0] || 'מאמרים';

  rows.push({ sourcePostId, title, slug, excerpt, content, category, publishedAt });
}

const valuesSql = rows
  .map(
    (r) =>
      `  (${r.sourcePostId}, ${sqlEscape(r.title)}, ${sqlEscape(r.slug || null)}, ${sqlEscape(r.excerpt)}, ${sqlEscape(r.content)}, ${sqlEscape(r.category)}, ${sqlEscape(r.publishedAt)})`,
  )
  .join(',\n');

const sql = `-- ============================================================
-- Seed blog_posts from the legacy WordPress WXR export.
-- Generated by scripts/blog-import/parse-wxr.mjs — do not edit by hand.
-- Re-run the script to regenerate; upserts on source_post_id.
-- ============================================================
BEGIN;

INSERT INTO public.blog_posts (
  source_post_id, title, slug, excerpt, content, category, published_at
) VALUES
${valuesSql}
ON CONFLICT (source_post_id) DO UPDATE SET
  title        = EXCLUDED.title,
  slug         = EXCLUDED.slug,
  excerpt      = EXCLUDED.excerpt,
  content      = EXCLUDED.content,
  category     = EXCLUDED.category,
  published_at = EXCLUDED.published_at;

NOTIFY pgrst, 'reload schema';

COMMIT;
`;

writeFileSync(outputPath, sql);

console.log(`Parsed ${rows.length} posts (skipped: ${skipped.drafts} drafts, ${skipped.attachments} attachments).`);
console.log(`Wrote ${outputPath}`);
