-- ============================================================
-- Backfill blog_posts.image_url from the WordPress WXR's
-- _thumbnail_id / attachment mapping. Generated by
-- scripts/blog-import/extract-featured-images.mjs — do not edit by hand.
--
-- URLs still point at kingdavid4u.co.il/wp-content/uploads; good enough
-- while the legacy site is up. Migrate to Supabase Storage in a follow-up.
-- ============================================================
BEGIN;

UPDATE public.blog_posts SET image_url = 'https://kingdavid4u.co.il/wp-content/uploads/2023/10/file.png' WHERE source_post_id = 11777;
UPDATE public.blog_posts SET image_url = 'https://kingdavid4u.co.il/wp-content/uploads/2021/10/20624.webp' WHERE source_post_id = 11792;
UPDATE public.blog_posts SET image_url = 'https://kingdavid4u.co.il/wp-content/uploads/2021/09/2134.webp' WHERE source_post_id = 11803;
UPDATE public.blog_posts SET image_url = 'https://kingdavid4u.co.il/wp-content/uploads/2024/01/1704900330.jpg' WHERE source_post_id = 11808;
UPDATE public.blog_posts SET image_url = 'https://kingdavid4u.co.il/wp-content/uploads/2021/09/46807.webp' WHERE source_post_id = 11819;
UPDATE public.blog_posts SET image_url = 'https://kingdavid4u.co.il/wp-content/uploads/2021/09/18678.webp' WHERE source_post_id = 11826;
UPDATE public.blog_posts SET image_url = 'https://kingdavid4u.co.il/wp-content/uploads/2021/09/18827149.webp' WHERE source_post_id = 11827;
UPDATE public.blog_posts SET image_url = 'https://kingdavid4u.co.il/wp-content/uploads/2024/06/145385.webp' WHERE source_post_id = 15757;
UPDATE public.blog_posts SET image_url = 'https://kingdavid4u.co.il/wp-content/uploads/2024/08/7085.webp' WHERE source_post_id = 15848;
UPDATE public.blog_posts SET image_url = 'https://kingdavid4u.co.il/wp-content/uploads/2024/10/pikaso_edit_Candid-image-photography-natural-textures-highly-r.webp' WHERE source_post_id = 15869;

COMMIT;
